"""Clearly synthetic patient results used only to preview the interface."""


DEMO_DISCLAIMER = "Synthetic demo prediction — not a real medical diagnosis."

DEMO_PATIENTS = [
    {
        "patient_name": "Ananya Rao",
        "age": 29,
        "gender": "Female",
        "clinical_risk_factors": ["HPV negative", "Non-smoker", "No family history"],
        "symptoms": "None reported",
        "screening_history": "Previous screening: Normal",
        "predicted_cell_class": "Superficial-Intermediate",
        "predicted_disease": None,
        "disease_probability": None,
        "disease_classification_result": "Not available — dataset labels are cell classes only",
        "selected_model": "ResNet50",
        "model_confidence": 0.962,
        "resnet50_confidence": 0.962,
        "efficientnet_b0_confidence": 0.948,
        "ensemble_confidence": 0.957,
        "early_risk_probability": 0.12,
        "risk_category": "Low",
        "clinical_factors": ["HPV negative", "Normal previous screening", "No reported symptoms"],
        "result_summary": "No significant abnormal pattern detected in this demo.",
        "gradcam_path": "/assets/demo-gradcam.svg",
        "is_demo_prediction": True,
        "disclaimer": DEMO_DISCLAIMER,
    },
    {
        "patient_name": "Kavya Sharma",
        "age": 36,
        "gender": "Female",
        "clinical_risk_factors": ["HPV status unknown", "Occasional alcohol use", "Screening overdue"],
        "symptoms": "Abnormal bleeding",
        "screening_history": "Previous screening: More than 3 years ago",
        "predicted_cell_class": "Metaplastic",
        "predicted_disease": None,
        "disease_probability": None,
        "disease_classification_result": "Not available — dataset labels are cell classes only",
        "selected_model": "EfficientNet-B0",
        "model_confidence": 0.914,
        "resnet50_confidence": 0.876,
        "efficientnet_b0_confidence": 0.914,
        "ensemble_confidence": 0.902,
        "early_risk_probability": 0.48,
        "risk_category": "Medium",
        "clinical_factors": ["Abnormal bleeding", "HPV status unknown", "Screening interval exceeds 3 years"],
        "result_summary": "Abnormal cell pattern requires clinical review in this demo.",
        "gradcam_path": "/assets/demo-gradcam.svg",
        "is_demo_prediction": True,
        "disclaimer": DEMO_DISCLAIMER,
    },
    {
        "patient_name": "Priya Nair",
        "age": 44,
        "gender": "Female",
        "clinical_risk_factors": ["HPV positive", "Current smoker", "Family history reported"],
        "symptoms": "Pelvic discomfort",
        "screening_history": "Previous screening: Abnormal",
        "predicted_cell_class": "Koilocytotic",
        "predicted_disease": None,
        "disease_probability": None,
        "disease_classification_result": "Not available — dataset labels are cell classes only",
        "selected_model": "Ensemble",
        "model_confidence": 0.941,
        "resnet50_confidence": 0.928,
        "efficientnet_b0_confidence": 0.935,
        "ensemble_confidence": 0.941,
        "early_risk_probability": 0.78,
        "risk_category": "High",
        "clinical_factors": ["HPV positive", "Abnormal previous screening", "Pelvic discomfort", "Current smoking"],
        "result_summary": "High-risk screening flag generated in this demo.",
        "gradcam_path": "/assets/demo-gradcam.svg",
        "is_demo_prediction": True,
        "disclaimer": DEMO_DISCLAIMER,
    },
    {
        "patient_name": "Meera Joshi",
        "age": 32,
        "gender": "Female",
        "clinical_risk_factors": ["HPV negative", "Non-smoker", "No family history"],
        "symptoms": "Mild discharge",
        "screening_history": "Previous screening: Normal",
        "predicted_cell_class": "Parabasal",
        "predicted_disease": None,
        "disease_probability": None,
        "disease_classification_result": "Not available — dataset labels are cell classes only",
        "selected_model": "ResNet50",
        "model_confidence": 0.896,
        "resnet50_confidence": 0.896,
        "efficientnet_b0_confidence": 0.867,
        "ensemble_confidence": 0.889,
        "early_risk_probability": 0.34,
        "risk_category": "Medium",
        "clinical_factors": ["Mild discharge", "HPV negative", "Normal previous screening"],
        "result_summary": "Further clinical review suggested in this demo.",
        "gradcam_path": "/assets/demo-gradcam.svg",
        "is_demo_prediction": True,
        "disclaimer": DEMO_DISCLAIMER,
    },
    {
        "patient_name": "Sneha Reddy",
        "age": 51,
        "gender": "Female",
        "clinical_risk_factors": ["HPV status unknown", "Former smoker", "Family history reported"],
        "symptoms": "Abnormal bleeding",
        "screening_history": "Previous screening: Not available",
        "predicted_cell_class": "Dyskeratotic",
        "predicted_disease": None,
        "disease_probability": None,
        "disease_classification_result": "Not available — dataset labels are cell classes only",
        "selected_model": "Ensemble",
        "model_confidence": 0.933,
        "resnet50_confidence": 0.921,
        "efficientnet_b0_confidence": 0.930,
        "ensemble_confidence": 0.933,
        "early_risk_probability": 0.84,
        "risk_category": "High",
        "clinical_factors": ["Abnormal bleeding", "Screening history unavailable", "Former smoking", "Family history"],
        "result_summary": "High-risk screening flag generated in this demo.",
        "gradcam_path": "/assets/demo-gradcam.svg",
        "is_demo_prediction": True,
        "disclaimer": DEMO_DISCLAIMER,
    },
]
